name: SHACL validation

on:
  workflow_call:
  push:
    paths:
      - 'ontology-combined.ttl'
  pull_request:
    paths:
      - 'ontology-combined.ttl'
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: SHACL validation
        run: |
          uv run python tools/python/checks/shacl.py ontology-combined.ttl src/quality-checks/shacl-shacl.ttl
