name: Conversion

on:
  release:
    types:
      - published

jobs:
  conversion-nt:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          git clone https://github.com/pchampin/sophia-cli
          cd sophia-cli
          cargo install --path .
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Convert ontology to N-Triples
        run: |
          sop parse src/ontology/ontology-combined.ttl ! serialize -o ontology-combined.nt
          sop parse src/ontology/ontology-combined-verbose.ttl ! serialize -o ontology-combined-verbose.nt

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.event.release.tag_name }}" src/ontology/ontology-combined.ttl ontology-combined.nt src/ontology/ontology-combined-verbose.ttl ontology-combined-verbose.nt --clobber
